<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Prueba</title>
</head>
<body>

<?php //echo $this->escape("Asset ID:".$this->assets->getId()); ?>
<!--<br/>-->
<?php //echo $this->escape("AssetType ID:".print_r($this->assets->getObjAssetType()))?>


<?php //foreach ($this->assets as $eachAsset): ?>
<!---->
<?php //endforeach ?>

<!--<h3>-------------Empieza Division-----------</h3>-->
<?php //foreach ($this->divisionsOfADiscipline as $eachDivision):?>
<!--    --><?php //echo $this->escape("División ID:".$eachDivision->getId()); ?><!-- <br/>-->
<!--    --><?php //echo $this->escape("Nombre :".$eachDivision->getName()); ?><!-- <br/>-->
<!--    --><?php //echo $this->escape("ID Disciplina :".$eachDivision->getObjDiscipline()->getId()); ?><!-- <br/>-->
<!--    -->
<?php //echo $this->escape("Nombre Disciplina:".$eachDivision->getObjDiscipline()->getName()); ?><!-- <br/>-->
<!---->
<?php //endforeach ?>
<!---->
<!--<h3>-------------Termina Division-----------</h3>-->
<!---->
<!---->
<!--<h3>-------------Empieza Propiedades-----------</h3>-->
<?php //foreach ($this->propertiesOfAnAsset as $eachProperty):?>
<!--    --><?php //echo $this->escape("Propiedad ID:".$eachProperty->getId()); ?><!-- <br/>-->
<!--    --><?php //echo $this->escape("Nombre :".$eachProperty->getName()); ?><!-- <br/>-->
<!--    --><?php //echo $this->escape("Tipo :".$eachProperty->getType()); ?><!-- <br/>-->
<!--    --><?php //echo $this->escape("Requerido? :".$eachProperty->isRequired()); ?><!-- <br/>-->
<!---->
<?php //endforeach ?>
<!--<h3>-------------Termina Propiedades-----------</h3>-->
<!---->
<?php //foreach ($this->assets as $eachAsset):?>
<!--    <h3>-------------Empieza un Asset-----------</h3>-->
<!--    --><?php //echo $this->escape("Activo ID:".$eachAsset->getId()); ?><!-- <br/>-->
<!--    --><?php //echo $this->escape("Nombre: ".$eachAsset->getName()); ?><!--<br/>-->
<!--    <br/>-->
<!--    --><?php //echo $this->escape("División ID: ".$eachAsset->getObjDivision()->getId()); ?><!--<br/>-->
<!--    --><?php //echo $this->escape("División Nombre ID: ".$eachAsset->getObjDivision()->getName()); ?><!--<br/>-->
<!--    <br/>-->
<!--    -->
<?php //echo $this->escape("Disciplina ID: ".$eachAsset->getObjDivision()->getObjDiscipline()->getId()); ?><!--<br/>-->
<!--    --><?php //echo $this->escape("Disciplina nombre: ".$eachAsset->getObjDivision()->getObjDiscipline()->getName()); ?>
<!---->
<!--    <br/><br/>-->
<!---->
<!--    --><?php //foreach ($eachAsset->getArrayProperties() as $entry):?>
<!---->
<!--        --><?php //echo $this->escape("Propiedades Id: ".$entry->getId()); ?>
<!--        --><?php //echo $this->escape("  ".$entry->getName()); ?>
<!--        --><?php //echo $this->escape(" ".$entry->getType()); ?>
<!--        --><?php //echo $this->escape(" ".$entry->isRequired()); ?>
<!---->
<!--        <br/>-->
<!---->
<!---->
<!--    --><?php //endforeach ?>
<!--    <h3>-------------Termina un Asset-----------</h3>-->
<?php //endforeach ?>


</body>
</html>